### ISSUE TITLE
exclude vendor

### ISSUE THREAD

**Issue by keradus** [dericofilho/php.tools#22]
Hi, what do you think about excluding vendor dir from project?

**Comment by dericofilho** [comment]
I am using Go's vendoring strategy - actually there are missing things in vendor dir, which I shall add as soon as I understand all dependencies licenses.

Therefore, vendor/ is staying.

**Comment by jimmypuckett** [comment]
@dericofilho I know that this is closed, but can you explain the reason behind using "Go's vendoring strategy" as it seems vastly different from most php packages.

**Comment by dericofilho** [comment]
@jimmypuckett I appreciate your interest in this design decision. You are
right, it vastly differs.

Personally I have been burnt by this whole composer and vendor thing few
times. Namely, dependencies not available any more, need to run (or modify)
PHP applications in network isolated and heavily filtered environments, and
versions not being perfectly honoured by composer.lock

Maybe I am too old fashioned, but I remember of a time that all
dependencies of an application would be embedded to it - or worst case it
relied on an external runtime binary to execute.

This vendoring strategy aims to not break too much with what the
overwhelming majority of composer users are used to. But when you download
php.tools for development, you know, right out of the box that it is ready
both to be used and modified - even if you don't use composer.

Just to make a point, as of the moment that I write this, Github is
unicorning, so essentially all the composer ecosystem is down for 15min.
Except, php.tools of course.

**Comment by jimmypuckett** [comment]
@dericofilho I understand.  I am using the package in a code generator that I am using, which has many other packages, so if github or packagist is down, the app won't work anyway.  I too have been bitten by the annoying package disappearing, so I see what you are thinking.

I do have something for you to consider...

Maybe have the code formatting in a package & the cli tool in another package.  I could see the /vendor being in the cli tool but not it the formatting package.

Thanks again for the work that you have done.

**Comment by dericofilho** [comment]
@jimmypuckett I will consider the idea for the next major release. No promises.

**Comment by keradus** [comment]
BTW, PHP CS Fixer approach is something between.
When one want to contribute or include package into his own etc - we give him only composer.json file and ask to take care of deps by himself. That way he could download it where he want - in cloned repo, in global composer dir to be shared with all other stuff he uses etc.

But then, we also offer a .phar package, which include all deps indeed. Then there is no risk of missing package etc during simply using a tool

**Comment by dericofilho** [comment]
@keradus sensitive to people who are only interested in using the formatter, I release phar packages on every release. 

https://github.com/dericofilho/php.tools/releases

**Comment by ccirello** [comment]
@jimmypuckett leftpad scandal proved my point here.
