### ISSUE TITLE
LaravelStyle->allmanStyleBraces() misbehave with Laravel src

### ISSUE THREAD

**Issue by piengeng** [dericofilho/php.tools#24]
save with laravel enabled on below file
https://github.com/laravel/framework/blob/4.2/src/Illuminate/Foundation/Application.php
seeing strange bracket location without indent as below shows.
```

	/**
	 * Register all of the base service providers.
	 *
	 * @return void
	 */
	protected function registerBaseServiceProviders()
	{
		foreach (array('Event', 'Exception', 'Routing') as $name)
		{
			$this->{"register{$name}Provider"}();
		}
	}

	/**
	 * Register the exception service provider.
	 *
	 * @return void
	 */
	protected function registerExceptionProvider()
{
		$this->register(new ExceptionServiceProvider($this));
	}

```

**Comment by dericofilho** [comment]
@piengeng I am really sorry for this bug. I can work on this, but I see you are already on charge for #23 . Do you want to take this over? Or do you want me to take care of this?

**Comment by piengeng** [comment]
@dericofilho would be nice if you can take over this, then i'll take over other issue when time comes, hehe

**Comment by dericofilho** [comment]
@piengeng OK! If you need any help, just let me know.

**Comment by dericofilho** [comment]
@piengeng Fixed. Please, I should like to have your feedback before closing this issue.

**Comment by piengeng** [comment]
that's quick, you'll need to give me some time. i'll get back to you once i'm done with the test. just fixed the PHP Notice in my code  #*&$)(@&#

**Comment by dericofilho** [comment]
@piengeng no problem. Just comment on the proper issue what you need help with.

**Comment by piengeng** [comment]
I'm failing the test, the output is different between ```php test.php -v``` and running from sublime-text..
i'm running windows 7, not sure if this is the case why the test is failing..

**Comment by dericofilho** [comment]
@piengeng the best is to use the command line to test the change... Something like this:

```
# cd src
# php fmt.src.php --laravel -o=- tests/###-FiLE-TEST.in
```

After you are done, you run
```
# php test.php -v
```

If all other tests don't fail, then you build with: 
```
# php build.php
```

Be sure to add all files in the commit.

**Comment by piengeng** [comment]
264-laravel-style-a.out-got <-- how do i get this *.out-got file?
php fmt.src.php --laravel -o=- tests/###-FiLE-TEST.in seems to generate the write output. but the out-got file always say differently... is it cached? if yes how do i clear it?

**Comment by dericofilho** [comment]
> 264-laravel-style-a.out-got <-- how do i get this *.out-got file?

It is a temporary file which `test.php` creates to compare with the `.out` one. You will not be able to see this file, because it is a temporary file.


try this instead:
`php fmt.src.php --laravel -o=tests/###-FiLE-TEST.out tests/###-FiLE-TEST.in`

**Comment by piengeng** [comment]
pls ignore my latest push, i believe my tests/264-laravel-style-a.out is the correct version. Will clone in linux and run test again..

**Comment by piengeng** [comment]
```php fmt.src.php --laravel -o=tests/###-FiLE-TEST.out tests/###-FiLE-TEST.in ```
do generates the correct out file. still failing the ```php test.php -v``` both in windows and linux.. sigh~

**Comment by dericofilho** [comment]
Please paste in a gist the full output

**Comment by piengeng** [comment]
https://gist.github.com/piengeng/117163b3c5036f1f49df

**Comment by piengeng** [comment]
i know where the region in my code is causing the failure, i just can't figure out why...

**Comment by dericofilho** [comment]
Try this `php fmt.src.php --enable_auto_align --laravel -o=tests/###-FiLE-TEST.out tests/###-FiLE-TEST.in`

It turns out the AlignDoubleArrow and AlignEquals are core passes, they are always executed. The `--enable_auto_align` should do the trick.

**Comment by piengeng** [comment]
the output from the test.php is not the expected output, and i always generate the correct output with 
```php fmt.src.php --laravel -o=tests/264-laravel-style-a.out tests/264-laravel-style-a.in```

**Comment by dericofilho** [comment]
The tests usually forces through all core passes plus any additional pass you declare. What's happening is that `.in` is being formatted with the core passes, which includes AlignDoubleArrow and AlignEquals. That's why I suggested you to call with `--enable_auto_align`.

**Comment by piengeng** [comment]
you're right, --enable_auto_align fixed the test. Anyhow, that is not the correct output. because the auto align i'm using is a bit different. maybe we'll just ignore it.

**Comment by dericofilho** [comment]
That's what I suggested in the code review few hours ago. Either reuse these passes or leave them out altogether. But PR is yours, you decide.
