### ISSUE TITLE
LaravelStyle->allmanStyleBraces() misbehave with Laravel src

### ISSUE THREAD

**Issue by piengeng** [dericofilho/php.tools#25]
```
Route::filter('guest', function()
{
	if (Auth::check()) return Redirect::to('/');
});
``` 
becomes
```
Route::filter('guest', function ()
{
	if (Auth::check())
	{return Redirect::to('/');
	}

});
```
@dericofilho need your help again...

**Comment by dericofilho** [comment]
@piengeng I am really sorry for this bug. Please manually update to https://github.com/dericofilho/sublime-phpfmt/commit/f1bc8be0bfd0f86850288d04ab102e17bed58887

**Comment by dericofilho** [comment]
@piengeng ping

**Comment by piengeng** [comment]
yes?

**Comment by dericofilho** [comment]
@piengeng Have you tested the fix for this? if so? May I close this issue?

**Comment by piengeng** [comment]
i only tested by manually adding ```$fmt->addPass(new SmartLnAfterCurlyOpen())```; in my test script, so, i'd say it's working, pls close this, there's a lot modification on https://github.com/dericofilho/php.tools/commit/ed5477b699537ec5724de68c1e54df1f29d2de6d though.
