### ISSUE TITLE
Error with properties when using --setters_and_getters=camel

### ISSUE THREAD

**Issue by jimmypuckett** [dericofilho/php.tools#30]
I have a file that is generated from Wsdl2PhpGenerator, 

```php
<?php

namespace Spinen\ConnectWiseApi\Wrappers\ActivityApi;

class Activity
{

    /**
     * @var string $CompanyIdentifier
     */
    protected $CompanyIdentifier = null;

    /**
     * @var int $Id
     */
    protected $Id = null;

    /**
     * @var string $Subject
     */
    protected $Subject = null;

// CUT OFF HERE TO MAKE SHORTER
}
```

which I want to run through the formatter, and when I format it with --setters_and_getters=camel I get

```php
<?php

namespace Spinen\ConnectWiseApi\Wrappers\ActivityApi;

class Activity {

	/**
	 * @var string $CompanyIdentifier
	 */
	protected $CompanyIdentifier; = null;

	/**
	 * @var int $Id
	 */
	protected $Id; = null;

	/**
	 * @var string $Subject
	 */
	protected $Subject; = null;

	/**
	 * @var string $Status
	 */
	protected $Status; = null;

// CUT OFF HERE TO MAKE SHORTER
}
```

Notice the ";" after the properties.

**Comment by dericofilho** [comment]
@jimmypuckett I am really sorry for this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@jimmypuckett please, update to https://github.com/dericofilho/php.tools/commit/9720d9c4c64a8eceed76f69c0a728d3e4ab7f4e0 
I will wait for your feedback before issuing a release.

**Comment by jimmypuckett** [comment]
Almost...

So, that does appear to have fixed the ";", but it made all of the other formatting stop working.  The tabbing is no longer 4 spaces, the alignment is not working, etc.

Even if I don't run it with the --setters_and_getters, the other stuff is now broken.

**Comment by dericofilho** [comment]
Please, provide me with the exact incantation you are using.  I could not reproduce this last behavior you described.

**Comment by jimmypuckett** [comment]
@dericofilho, seems to be working great.  Sorry for the false alarm.

**Comment by dericofilho** [comment]
@jimmypuckett thanks for using the plugin.
