### ISSUE TITLE
how can I get the current version info ?

### ISSUE THREAD

**Issue by wwb-dev** [dericofilho/php.tools#32]
the help info doesn't provided.

**Comment by dericofilho** [comment]
@wwb-dev I am sorry for this inconvenience. I will fix it ASAP.

**Comment by dericofilho** [comment]
@wwb-dev update to https://github.com/dericofilho/php.tools/commit/b1fb09381b1dd3ee748b5a07976b49b7294d01d5

Is this what you need?

**Comment by dericofilho** [comment]
@wwb-dev Fixed at [7.9.1](https://github.com/dericofilho/php.tools/releases/tag/7.9.1)

```
$ ./fmt.phar --version
./fmt.phar 7.9.1
```

**Comment by wwb-dev** [comment]
thanks
