### ISSUE TITLE
parenthesis where they do not belong, yoda adds

### ISSUE THREAD

**Issue by vith** [dericofilho/php.tools#36]
As far as I can tell this only happens with yoda mode and method calls inside a `"{$ref}"` interpolation. The `if` test preceding the interpolation is also necessary to trigger the bug, and it wouldn't happen outside of a class when I tried.

# Version
`dericofilho/fmt 7.21.1`

# Command Line
```shell
fmt.php --yoda interp.php
```

# Input
```php
<?php

namespace Parenthesis;

class FromOutOfNowhere {
	public static function hereItComes() {
		if (null !== $this) {
			return;
		}

		$this->announce("Hello: {$this->goodbye()}");
	}
}
```

# Output
```php
<?php

namespace Parenthesis;

class FromOutOfNowhere {
	public static function hereItComes() {
		if (null !== $this) {
			return;
		}

		$this->announce("Hello: {$this->goodbye())}");
	}
}
```

**Comment by dericofilho** [comment]
@vith I am sorry for this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@vith please, upgrade to https://github.com/dericofilho/php.tools/releases/tag/7.21.2

**Comment by vith** [comment]
The fix works for me. Thanks.
