### ISSUE TITLE
how to use it in sublime text3?

### ISSUE THREAD

**Issue by ioriandy4** [dericofilho/php.tools#41]
how to use it in sublime text3?

**Comment by dericofilho** [comment]
@ioriandy4 usa phpfmt plugin from package control

**Comment by ioriandy4** [comment]
I install it from package control but i don't know how to use it.I should use which keys?

**Comment by dericofilho** [comment]
@ioriandy4 have you followed installation procedures in sublime-phpfmt README.md? including having a valid PHP 5.6 local installation?

**Comment by dericofilho** [comment]
@ioriandy4  https://github.com/dericofilho/sublime-phpfmt#installation

**Comment by ioriandy4** [comment]
![01](https://cloud.githubusercontent.com/assets/7553775/8284065/7f604490-192d-11e5-9e49-3a63fa4ba248.png)
what is going on?

**Comment by dericofilho** [comment]
@ioriandy4 the JSON is malformed. Add a comma after `"version": 2` and remove the comma in the end of line 3.

**Comment by dericofilho** [comment]
@ioriandy4 php.tools needs at least PHP 5.6 this PHP you said will not work.

**Comment by ioriandy4** [comment]
oh , 5.6 is too new

**Comment by dericofilho** [comment]
You can install a PHP 5.6 separated from your local deployment. Maybe in `D:/php5.6/`

If you are not willing to install PHP 5.6, please consider using https://packagecontrol.io/packages/Phpcs

**Comment by dericofilho** [comment]
@ioriandy4 I added a support a PHP 5.5 compatibility mode.

**Comment by ioriandy4** [comment]
@dericofilho  it can use in PHP 5.5 now?

**Comment by dericofilho** [comment]
@ioriandy4 yes, it can. You should install this version though, https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.4.0

**Comment by ioriandy4** [comment]
the version can't work,i insall it and use ctrl+shift+p, then i can't find the commands about the phpfmt

**Comment by dericofilho** [comment]
@ioriandy4 please, open a new issue with your configuration file and console output.
Add `"debug":true` to the configuration file, so to expose debug internals in the console output.

**Comment by dericofilho** [comment]
@ioriandy4 also, open the issue at https://github.com/dericofilho/sublime-phpfmt not here.
