### ISSUE TITLE
PSR2 camelCase conversion is too abusive

### ISSUE THREAD

**Issue by iamntz** [dericofilho/php.tools#42]
Hi, I just discovered these tools (As a [sublime plugin](https://github.com/dericofilho/sublime-phpfmt), but I assume the problem resides here) and I noticed a small issue:

```php
	public function add_meta_box() // <-- this should be converted to camel case
	{
		add_meta_box( /* unnecessary code */ );
		// ^--- this one should remain as it is
	}
```

I think this could be solved by changing scopes:

method definition scope (also match the non OOP function definition):
![2015-07-10 31_50](https://cloud.githubusercontent.com/assets/132062/8627404/8d299cc8-2753-11e5-93cb-acb3ef444c79.jpg)

function call scope:
![2015-07-10 32_01](https://cloud.githubusercontent.com/assets/132062/8627403/88c20170-2753-11e5-9686-1c299d9f8d63.jpg)

**Comment by dericofilho** [comment]
@iamntz I am sorry for this inconvenience. Have you considered using `phpfmt: toggle PSR1 - Class and Methods names`. It will do exactly what you have just asked.

**Comment by dericofilho** [comment]
@iamntz in pure php.tools case, just don't invoke `--psr1-naming`

**Comment by iamntz** [comment]
:+1: 

I think i missed that, this helps, thanks!
