### ISSUE TITLE
Adding new formatting rules

### ISSUE THREAD

**Issue by iamntz** [dericofilho/php.tools#46]
There is an easy way of adding new formatting rules?

E.g. https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/ 

Thanks!

**Comment by dericofilho** [comment]
@iamntz Hi, I am sorry for this inconvenience. I am going to write a first draft for your use. Together we'll improve it.

**Comment by dericofilho** [comment]
@iamntz please, check this out: https://github.com/dericofilho/php.tools/blob/master/COOKBOOK.md

**Comment by iamntz** [comment]
Oh, wow, thanks! Looks very helpful (although I was hoping to something more... extensible).

Will give a try these days!

**Comment by dericofilho** [comment]
@iamntz  What do you mean by?
> although I was hoping to something more... extensible

**Comment by iamntz** [comment]
Well, I was hoping that i could add a new definition by not having to re-generate all thing. More like a plugin, or something like this. But I guess is not a biggie :)

**Comment by dericofilho** [comment]
@iamntz patches are welcome :)
